Feature/pdct 1564 update the mcf landing page hero
climatepolicyradar/navigator-frontend pull request #224
Opened 2024-10-14 15:57 UTC by odrakes-cpr

# What's changed

## Proposed version

Please select the option below that is most relevant from the list below. This
will be used to generate the next tag version name during auto-tagging.

Add Hero to MCF landing page

- [ ] Skip auto-tagging
- [x] Patch
- [ ] Minor version
- [ ] Major version

Visit the [Semver website](https://semver.org/#summary) to understand the
difference between `MAJOR`, `MINOR`, and `PATCH` versions.

Notes:

- If none of these options are selected, auto-tagging will fail
- Where multiple options are selected, the most senior option ticked will be
  used -- e.g. Major > Minor > Patch
- If you are selecting the version in the list above using the textbox, make
  sure your selected option is marked `[x]` with no spaces in between the
  brackets and the `x`

2024-10-14 16:01 UTC, odrakes-cpr commented
<img width="1352" alt="Screenshot 2024-10-14 at 17 01 09" src="https://github.com/user-attachments/assets/a61b05eb-7227-46af-9ad6-11ad14cc0168">

2024-10-15 08:18 UTC, PatFawbertMills requested changes
Minor thing with memory saver

2024-10-15 08:18 UTC, PatFawbertMills commented on themes/mcf/components/HeroComponents/MultilateralClimateFundsLogos.tsx
> +  const fundInformation: FundData[] = [
Define collection outside of the component else it will redefine it on every re-render

2024-10-15 08:18 UTC, PatFawbertMills commented on themes/mcf/styles/styles.scss
> +  background: linear-gradient(to right, #24a5b6, #27a049, #eac859, #f79d03, #39b45e);
Nice, look forward to seeing it!

2024-10-15 09:45 UTC, annaCPR approved these changes
lgtm

2024-10-15 09:47 UTC, merged