Feature/pdct 1602 create metadata renderer component for document page
climatepolicyradar/navigator-frontend pull request #238
Opened 2024-10-25 10:52 UTC by odrakes-cpr

# What's changed

## Proposed version

Please select the option below that is most relevant from the list below. This
will be used to generate the next tag version name during auto-tagging.

- [ ] Skip auto-tagging
- [x] Patch
- [ ] Minor version
- [ ] Major version

Visit the [Semver website](https://semver.org/#summary) to understand the
difference between `MAJOR`, `MINOR`, and `PATCH` versions.

Notes:

- If none of these options are selected, auto-tagging will fail
- Where multiple options are selected, the most senior option ticked will be
  used -- e.g. Major > Minor > Patch
- If you are selecting the version in the list above using the textbox, make
  sure your selected option is marked `[x]` with no spaces in between the
  brackets and the `x`

2024-10-28 12:03 UTC, odrakes-cpr commented
![Screenshot 2024-10-28 at 11 54 28](https://github.com/user-attachments/assets/c2afd6a5-74cb-4a41-b7b8-33e2a329f995)

2024-10-28 14:42 UTC, PatFawbertMills requested changes
Couple of things

2024-10-28 14:42 UTC, PatFawbertMills commented on src/components/documents/DocumentHead.tsx
> +          <div className="flex-1 my-4 max-w-[1100px]">
We shouldn't be setting containers in this way, that was the whole point of the `sr/components/panels` component set.

Can you use the `SingleCol` component?

2024-10-28 14:42 UTC, PatFawbertMills commented on src/components/documents/renderers/DocumentMetaRenderer.tsx
> +const MultilateralClimateFunds = "MCF";
Make constants descriptive and in all uppercase so that they are easier to spot in the code please

2024-10-28 17:52 UTC, odrakes-cpr commented
Handle multiple values for implementing agencies and geographies


![Screenshot 2024-10-28 at 17 50 17](https://github.com/user-attachments/assets/a8d52e2e-58f0-40cb-beb0-8371cf9b7c9d)

2024-10-29 11:06 UTC, PatFawbertMills approved these changes
Nice work

2024-10-29 11:23 UTC, merged